
pdf:
	make -C abstract/ pdf
	make -C devel/ pdf
	make -C doc_user/ pdf
	make -C rapport/ pdf
clean:
	make -C abstract/ clean
	make -C devel/ clean
	make -C doc_user/ clean
	make -C rapport/ clean

.PHONY: clean pdf
